site_name: coincurve
site_description: Cross-platform Python bindings for libsecp256k1
site_author: Ofek Lev
site_url: https://ofek.dev/coincurve/
repo_name: ofek/coincurve
repo_url: https://github.com/ofek/coincurve
edit_uri: blob/master/docs
copyright: 'Copyright &copy; Ofek Lev 2017-present'

docs_dir: docs
site_dir: site
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/circle-multiple
    repo: fontawesome/brands/github-alt
  favicon: assets/images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections

nav:
  - About: index.md
  - Install: install.md
  - API Reference: api.md
  - Benchmarks: benchmarks.md
  - Meta:
    - Users: users.md
    - History: history.md

plugins:
  # Built-in
  search: {}
  # Extra
  glightbox: {}
  minify:
    minify_html: true
  git-revision-date-localized:
    type: date
    strict: false
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths:
          - src
        options:
          # Rendering
          show_root_full_path: false
          # Headings
          show_root_heading: true
          show_source: false
          show_symbol_type_toc: true
          # Docstrings
          show_if_no_docstring: true
          # Signatures/annotations
          show_signature_annotations: true
          signature_crossrefs: true
          # Other
          show_bases: false
        import:
          - https://docs.python.org/3/objects.inv

markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  # Extra
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      # https://github.com/twitter/twemoji
      # https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/pymdownx/twemoji_db.py
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: ofek
      repo: coincurve
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs/.snippets
      auto_append:
        - links.txt
        - abbrs.txt
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ofek
    - icon: fontawesome/solid/blog
      link: https://ofek.dev/words/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Ofekmeister
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ofeklev/
extra_css:
  - assets/css/custom.css
  - https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.css
