name: coincurve-with-conda-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - cffi >=1.3.0
  - cmake
  - libsecp256k1
  - pkg-config
  - pytest
  - pytest-benchmark
  - python =3.12
  - setuptools >=61
  - tox-conda
