from collections.abc import Iterable
from typing import TypeAlias, final

from coincurve.types import Hasher

ReadableBuffer: TypeAlias = bytes | bytearray | memoryview

@final
class PrivateKey:
    @property
    def secret(self) -> bytes: ...
    @property
    def public_key(self) -> PublicKey: ...
    @property
    def xonly_public_key(self) -> XOnlyPublicKey: ...
    def __init__(self, secret: ReadableBuffer | None = None) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    @classmethod
    def from_int(cls, value: int, /) -> PrivateKey: ...
    @classmethod
    def from_hex(cls, value: str, /) -> PrivateKey: ...
    @classmethod
    def from_der(cls, value: ReadableBuffer, /) -> PrivateKey: ...
    @classmethod
    def from_pem(cls, value: ReadableBuffer, /) -> PrivateKey: ...
    def to_int(self) -> int: ...
    def to_hex(self) -> str: ...
    def to_der(self) -> bytes: ...
    def to_pem(self) -> bytes: ...
    def sign(self, message: bytes, hasher: Hasher = ..., *, extra_entropy: ReadableBuffer | None = None) -> bytes: ...
    def sign_digest(self, digest: ReadableBuffer, *, extra_entropy: ReadableBuffer | None = None) -> bytes: ...
    def sign_recoverable(
        self, message: bytes, hasher: Hasher = ..., *, extra_entropy: ReadableBuffer | None = None
    ) -> bytes: ...
    def sign_recoverable_digest(
        self, digest: ReadableBuffer, *, extra_entropy: ReadableBuffer | None = None
    ) -> bytes: ...
    def sign_schnorr(self, message: ReadableBuffer, aux_randomness: ReadableBuffer | None = b"") -> bytes: ...
    def sign_schnorr_message(
        self, message: bytes, hasher: Hasher = ..., *, aux_randomness: ReadableBuffer | None = b""
    ) -> bytes: ...
    def sign_schnorr_digest(self, digest: ReadableBuffer, *, aux_randomness: ReadableBuffer | None = b"") -> bytes: ...
    def sign_many(
        self, messages: Iterable[bytes], hasher: Hasher = ..., *, extra_entropy: ReadableBuffer | None = None
    ) -> list[bytes]: ...
    def sign_digests(
        self, digests: Iterable[ReadableBuffer], *, extra_entropy: ReadableBuffer | None = None
    ) -> list[bytes]: ...
    def sign_recoverable_many(
        self, messages: Iterable[bytes], hasher: Hasher = ..., *, extra_entropy: ReadableBuffer | None = None
    ) -> list[bytes]: ...
    def sign_recoverable_digests(
        self, digests: Iterable[ReadableBuffer], *, extra_entropy: ReadableBuffer | None = None
    ) -> list[bytes]: ...
    def sign_schnorr_many(
        self, messages: Iterable[bytes], hasher: Hasher = ..., *, aux_randomness: ReadableBuffer | None = None
    ) -> list[bytes]: ...
    def sign_schnorr_digests(
        self, digests: Iterable[ReadableBuffer], *, aux_randomness: ReadableBuffer | None = None
    ) -> list[bytes]: ...
    def ecdh(self, peer_public_key: PublicKey | ReadableBuffer, /) -> bytes: ...
    def ecdh_many(self, peer_public_keys: Iterable[PublicKey], /) -> list[bytes]: ...
    def add(self, scalar: ReadableBuffer, /) -> PrivateKey: ...
    def multiply(self, scalar: ReadableBuffer, /) -> PrivateKey: ...

@final
class PublicKey:
    def __init__(self, data: ReadableBuffer) -> None: ...
    def __bytes__(self) -> bytes: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    @classmethod
    def from_secret(cls, secret: ReadableBuffer, /) -> PublicKey: ...
    @classmethod
    def from_point(cls, x: int, y: int) -> PublicKey: ...
    @classmethod
    def recover(cls, signature: ReadableBuffer, message: bytes, hasher: Hasher = ...) -> PublicKey: ...
    @classmethod
    def recover_digest(cls, signature: ReadableBuffer, digest: ReadableBuffer) -> PublicKey: ...
    @classmethod
    def combine_keys(cls, keys: Iterable[PublicKey], /) -> PublicKey: ...
    def format(self, compressed: bool = True) -> bytes: ...
    def point(self) -> tuple[int, int]: ...
    def verify(self, signature: ReadableBuffer, message: bytes, hasher: Hasher = ...) -> bool: ...
    def verify_digest(self, signature: ReadableBuffer, digest: ReadableBuffer) -> bool: ...
    def verify_many(
        self, signatures: Iterable[ReadableBuffer], messages: Iterable[bytes], hasher: Hasher = ...
    ) -> list[bool]: ...
    def verify_digests(self, signatures: Iterable[ReadableBuffer], digests: Iterable[ReadableBuffer]) -> list[bool]: ...
    def add(self, scalar: ReadableBuffer, /) -> PublicKey: ...
    def multiply(self, scalar: ReadableBuffer, /) -> PublicKey: ...
    def combine(self, keys: Iterable[PublicKey], /) -> PublicKey: ...

@final
class XOnlyPublicKey:
    @property
    def parity(self) -> bool | None: ...
    def __init__(self, data: ReadableBuffer, parity: bool | None = None) -> None: ...
    def __bytes__(self) -> bytes: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    @classmethod
    def from_secret(cls, secret: ReadableBuffer, /) -> XOnlyPublicKey: ...
    @classmethod
    def from_public_key(cls, public_key: PublicKey, /) -> XOnlyPublicKey: ...
    def format(self) -> bytes: ...
    def verify(self, signature: ReadableBuffer, message: ReadableBuffer) -> bool: ...
    def verify_message(self, signature: ReadableBuffer, message: bytes, hasher: Hasher = ...) -> bool: ...
    def verify_digest(self, signature: ReadableBuffer, digest: ReadableBuffer) -> bool: ...
    def verify_many(
        self, signatures: Iterable[ReadableBuffer], messages: Iterable[bytes], hasher: Hasher = ...
    ) -> list[bool]: ...
    def verify_digests(self, signatures: Iterable[ReadableBuffer], digests: Iterable[ReadableBuffer]) -> list[bool]: ...
    def tweak_add(self, scalar: ReadableBuffer, /) -> None: ...
    def add_tweak(self, scalar: ReadableBuffer, /) -> XOnlyPublicKey: ...

def verify_signature(
    signature: ReadableBuffer, message: bytes, public_key: ReadableBuffer, hasher: Hasher = ...
) -> bool: ...
def verify_signature_digest(signature: ReadableBuffer, digest: ReadableBuffer, public_key: ReadableBuffer) -> bool: ...
def der_to_compact(signature: ReadableBuffer, /) -> bytes: ...
def compact_to_der(signature: ReadableBuffer, /) -> bytes: ...
def normalize_signature(signature: ReadableBuffer, /) -> tuple[bool, bytes]: ...
def recoverable_to_der(signature: ReadableBuffer, /) -> bytes: ...
def _batch_sign_digests(private_keys: Iterable[PrivateKey], digests: Iterable[ReadableBuffer], /) -> list[bytes]: ...
def _batch_sign_recoverable_digests(
    private_keys: Iterable[PrivateKey], digests: Iterable[ReadableBuffer], /
) -> list[bytes]: ...
def _batch_sign_schnorr_digests(
    private_keys: Iterable[PrivateKey], digests: Iterable[ReadableBuffer], /
) -> list[bytes]: ...
def _batch_verify_digests(
    public_keys: Iterable[PublicKey], signatures: Iterable[ReadableBuffer], digests: Iterable[ReadableBuffer], /
) -> list[bool]: ...
def _batch_verify_schnorr_digests(
    public_keys: Iterable[XOnlyPublicKey], signatures: Iterable[ReadableBuffer], digests: Iterable[ReadableBuffer], /
) -> list[bool]: ...
def _batch_recover_digests(
    signatures: Iterable[ReadableBuffer], digests: Iterable[ReadableBuffer], /
) -> list[PublicKey | None]: ...
def _batch_ecdh(private_keys: Iterable[PrivateKey], public_keys: Iterable[PublicKey], /) -> list[bytes]: ...
def _batch_derive_public_keys(secrets: Iterable[ReadableBuffer], /) -> list[PublicKey]: ...
def _batch_derive_xonly_public_keys(secrets: Iterable[ReadableBuffer], /) -> list[XOnlyPublicKey]: ...
def _packed_derive_public_keys(secrets: ReadableBuffer, /) -> tuple[bytes, bytes]: ...
def _packed_derive_xonly_public_keys(secrets: ReadableBuffer, /) -> tuple[bytes, bytes]: ...
def _packed_sign_ecdsa_digests(secrets: ReadableBuffer, digests: ReadableBuffer, /) -> tuple[bytes, bytes]: ...
def _packed_sign_recoverable_digests(secrets: ReadableBuffer, digests: ReadableBuffer, /) -> tuple[bytes, bytes]: ...
def _packed_sign_schnorr_digests(secrets: ReadableBuffer, digests: ReadableBuffer, /) -> tuple[bytes, bytes]: ...
def _packed_verify_ecdsa_digests(
    public_keys: ReadableBuffer, signatures: ReadableBuffer, digests: ReadableBuffer, /
) -> bytes: ...
def _packed_verify_schnorr_digests(
    public_keys: ReadableBuffer, signatures: ReadableBuffer, digests: ReadableBuffer, /
) -> bytes: ...
def _packed_recover_public_keys(signatures: ReadableBuffer, digests: ReadableBuffer, /) -> tuple[bytes, bytes]: ...
def _packed_ecdh(secrets: ReadableBuffer, public_keys: ReadableBuffer, /) -> tuple[bytes, bytes]: ...
