function (UpdateVendoredLibraryOptions _prefix _newPrefix)
    get_cmake_property(_vars VARIABLES)
    string (REGEX MATCHALL "(^|;)${_prefix}[A-Za-z0-9_]*" _matchedVars "${_vars}")
    foreach (_var ${_matchedVars})
        string (REGEX REPLACE "^${_prefix}" "${_newPrefix}" _newVar ${_var})
        set(${_newVar} ${${_var}} PARENT_SCOPE)
        unset (${_var} PARENT_SCOPE)
    endforeach()
endfunction()
