from ._libsecp256k1 import lib

CONTEXT_SIGN = lib.SECP256K1_CONTEXT_SIGN
CONTEXT_VERIFY = lib.SECP256K1_CONTEXT_VERIFY
CONTEXT_ALL = CONTEXT_SIGN | CONTEXT_VERIFY
CONTEXT_NONE = lib.SECP256K1_CONTEXT_NONE
CONTEXT_FLAGS = {CONTEXT_SIGN, CONTEXT_VERIFY, CONTEXT_ALL, CONTEXT_NONE}

EC_COMPRESSED = lib.SECP256K1_EC_COMPRESSED
EC_UNCOMPRESSED = lib.SECP256K1_EC_UNCOMPRESSED
