name: shared_build

on:
  push:
    tags:
    - v*
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: shared-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

env:
  PYTHON_VERSION: '3.14'
  COINCURVE_IGNORE_SYSTEM_LIB: 'ON'
  COINCURVE_SECP256K1_STATIC: 'OFF'
  COINCURVE_CROSS_HOST: ''
  CIBW_BUILD: 'cp314-*'
  CIBW_ENVIRONMENT_PASS_LINUX: >
    COINCURVE_IGNORE_SYSTEM_LIB
    COINCURVE_SECP256K1_STATIC
    COINCURVE_CROSS_HOST
  CIBW_BEFORE_ALL_MACOS: ./.github/scripts/install-macos-build-deps.sh
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: >
    python -c
    "from coincurve import PrivateKey;
    a=PrivateKey();
    b=PrivateKey();
    assert a.ecdh(b.public_key.format())==b.ecdh(a.public_key.format())
    " &&
    python -m pytest {project}

jobs:
  linux-wheels-x86_64:
    name: Build shared Linux wheel for x86-64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Build wheel
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS_LINUX: x86_64

  linux-wheels-arm64:
    name: Build shared Linux wheel for ARM64
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v7

    - name: Build wheel
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS_LINUX: aarch64

  macos-wheels-x86_64:
    name: Build shared macOS wheel for x86-64
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v7

    - name: Build wheel
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS_MACOS: x86_64
        MACOSX_DEPLOYMENT_TARGET: '10.15'

  macos-wheels-arm64:
    name: Build shared macOS wheel for ARM64
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v7

    - name: Build wheel
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS_MACOS: arm64

  windows-wheels-x86_64:
    name: Build shared Windows wheel for x86-64
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7

    - name: Build wheel
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS_WINDOWS: AMD64
        CIBW_BEFORE_ALL: choco install -y --no-progress --no-color cmake>=3.28

  windows-wheels-arm64:
    name: Build shared Windows wheel for ARM64
    runs-on: windows-11-arm

    steps:
    - uses: actions/checkout@v7

    - name: Build wheel
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS_WINDOWS: ARM64
        CIBW_BEFORE_ALL: choco install -y --no-progress --no-color cmake>=3.28
